version: "3"
services:
  web:
    image: node:boron
    command: yarn dev
    working_dir: /usr/src/app
    tty: true
    ports:
      - "8000:8000"
      - "35729:35729"
    volumes:
      -  $PWD:/usr/src/app
